version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    volumes:
      - ./:/api-server/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: >
      bash -c 
      "go run cmd/main.go"
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=dev12341
      - POSTGRES_DB=base
    ports:
      - "5432:5432"

volumes:
  pg_data: {}



